server:
  dubbo:
    port:
      7888
  port: 9521
spring:
  sleuth:
    annotation:
      enabled: true
    trace-id128: true
    sampler:
      probability: 1.0
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.5:3306/fota?allowMultiQueries=true&characterEncoding=utf8&useUnicode=true
      username: fota
      password: fotapre
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /admin/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
            
  redis:
    cluster:
      nodes: 192.168.1.6:6379,192.168.1.6:6380,192.168.1.6:6381,192.168.1.11:6379,192.168.1.11:6380,192.168.1.11:6381
    lettuce:
      pool:
        max-active: 250
        max-wait: 500ms
        max-idle: 50
        min-idle: 10
  zookeeper:
    serverList: 192.168.1.62:2181


mybatis:
  mapper-locations: classpath:mapper/*.xml
management:
  server:
    port: 10004